// The app's pinning: the SPKI fingerprint it computes must be the one the box
// printed (lib/cert.py), and a wrong pin must not match. The fixture certificate
// (test/fixtures/relay-cert.pem) is a throwaway self-signed cert generated by the
// box's own lib/cert.py; the expected value below is what that generator printed.

import 'dart:io';

import 'package:test/test.dart';

import '../lib/transport.dart';

const String fixtureSpki = '2e8bbcd294fb72b6eff1a6a8159d6385591fa1845dec34458ff2e02778e4a597';

void main() {
  final pem = File('test/fixtures/relay-cert.pem').readAsStringSync();
  final der = derFromPem(pem);

  test('the fingerprint matches the box\'s own generator', () {
    expect(spkiFingerprintFromPem(pem), equals(fixtureSpki));
    expect(spkiFingerprintFromDer(der), equals(fixtureSpki));
  });

  test('a matching pin verifies, a wrong one does not', () {
    expect(spkiMatches(der, fixtureSpki), isTrue);
    expect(spkiMatches(der, fixtureSpki.toUpperCase()), isTrue, reason: 'hex case is irrelevant');
    final flipped = fixtureSpki.endsWith('0') ? '${fixtureSpki.substring(0, 63)}1' : '${fixtureSpki.substring(0, 63)}0';
    expect(spkiMatches(der, flipped), isFalse, reason: 'one nibble wrong must not match');
    expect(spkiMatches(der, 'nope'), isFalse, reason: 'a short pin must not match');
    // Colon-separated (the form a parent may copy) still matches; a same-length
    // wrong value does not.
    final colons = [
      for (var i = 0; i < fixtureSpki.length; i += 2) fixtureSpki.substring(i, i + 2),
    ].join(':');
    expect(spkiMatches(der, colons), isTrue, reason: 'colons are separators, not bytes');
    expect(spkiMatches(der, colons.replaceRange(0, 2, 'aa')), isFalse, reason: 'a same-length wrong pin must not match');
  });

  test('a non-certificate is refused', () {
    expect(() => spkiFingerprintFromDer([0x01, 0x02, 0x03]), throwsA(anything));
  });
}
