// The app's crypto must reproduce the box's shared vectors byte for byte
// (N-8): clients/parent/test-vectors/notify-vectors.json is generated by
// clients/parent/test-vectors/generate.py and checked by
// test/shell.d/notify-vectors-test.sh. This proves the Dart side matches too.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:test/test.dart';

import '../lib/notify_crypto.dart';

void main() {
  final doc = jsonDecode(File('test-vectors/notify-vectors.json').readAsStringSync()) as Map<String, dynamic>;

  test('the canonical form matches the box (including a non-ASCII reply)', () {
    final decision = (doc['decision'] as Map).cast<String, Object?>();
    final message = utf8.encode(canonicalJson(decision));
    final want = base64.decode(doc['decision_message_b64'] as String);
    // the recorded message is the context plus the canonical record
    expect(message, equals(want.sublist(signContext.length)));
    expect(utf8.decode(message), contains(r'Apr\u00e8s d\u00eener'));
  });

  test('the decision signature verifies over the canonical record', () async {
    final decision = (doc['decision'] as Map).cast<String, Object?>();
    final publicKey = SimplePublicKey(base64.decode(doc['sign_pub_b64'] as String), type: KeyPairType.ed25519);
    final signature = Signature(
      base64.decode(doc['decision_signature_b64'] as String),
      publicKey: publicKey,
    );
    final ok = await Ed25519().verify(decisionMessage(decision), signature: signature);
    expect(ok, isTrue);
  });

  test('the request signature verifies over the request message', () async {
    final request = (doc['request'] as Map).cast<String, dynamic>();
    final message = requestMessage(
      deviceId: request['device_id'] as String,
      ts: request['ts'] as int,
      nonce: request['nonce'] as String,
      method: request['method'] as String,
      path: request['path'] as String,
      body: base64.decode(request['body_b64'] as String),
    );
    expect(base64.encode(message), equals(doc['request_message_b64'] as String));
    final publicKey = SimplePublicKey(base64.decode(doc['sign_pub_b64'] as String), type: KeyPairType.ed25519);
    final signature = Signature(
      base64.decode(doc['request_signature_b64'] as String),
      publicKey: publicKey,
    );
    expect(await Ed25519().verify(message, signature: signature), isTrue);
  });

  test('the pairing proof recomputes from the token', () async {
    final pairing = (doc['pairing'] as Map).cast<String, String>();
    final proof = await pairingProof(
      pairing['token']!,
      pairing['name']!,
      pairing['sign_pub']!,
      pairing['box_pub']!,
    );
    expect(proof, equals(pairing['proof']));
  });

  test('the away envelope opens with the box private key', () async {
    final env = (doc['envelope'] as Map).cast<String, dynamic>();
    final plaintext = await Envelope.open(
      deviceId: 'd-vector',
      boxSeed: _hexToBytes(env['box_priv_hex'] as String),
      envelope: (env['envelope'] as Map).cast<String, Object?>(),
    );
    expect(plaintext, equals(base64.decode(env['plaintext_b64'] as String)));
  });

  test('the envelope rejects another device id (the AAD binds it)', () async {
    final env = (doc['envelope'] as Map).cast<String, dynamic>();
    final sealed = (env['envelope'] as Map).cast<String, Object?>();
    await expectLater(
      Envelope.open(
        deviceId: 'd-other',
        boxSeed: _hexToBytes(env['box_priv_hex'] as String),
        envelope: sealed,
      ),
      throwsA(anything),
    );
  });
}

Uint8List _hexToBytes(String hex) {
  final out = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}
