// The app's crypto must reproduce the box's shared vectors byte for byte
// (N-8): clients/parent/test-vectors/notify-vectors.json is generated by
// clients/parent/test-vectors/generate.py and checked by
// test/shell.d/notify-vectors-test.sh. This proves the Dart side matches too.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:test/test.dart';

import '../lib/notify_crypto.dart';
import '../lib/relay_client.dart';

void main() {
  final doc = jsonDecode(File('test-vectors/notify-vectors.json').readAsStringSync()) as Map<String, dynamic>;

  test('the canonical form matches the box (including a non-ASCII reply)', () {
    final decision = (doc['decision'] as Map).cast<String, Object?>();
    final message = utf8.encode(canonicalJson(decision));
    final want = base64.decode(doc['decision_message_b64'] as String);
    // the recorded message is the context plus the canonical record
    expect(message, equals(want.sublist(signContext.length)));
    expect(utf8.decode(message), contains(r'Apr\u00e8s \"d\u00eener\" \\ ok'));
  });

  test('the decision record the app builds is the box vector, byte for byte (amendment section 20)', () {
    final decision = (doc['decision'] as Map).cast<String, Object?>();
    final built = decisionRecord(
      deviceId: decision['device_id'] as String,
      requestId: decision['request_id'] as String,
      decision: decision['decision'] as String,
      ts: decision['ts'] as int,
      nonce: decision['nonce'] as String,
      reply: decision['reply'] as String?,
      kid: decision['kid'] as String,
      kind: decision['kind'] as String,
      what: decision['what'] as String,
      minutes: decision['minutes'] as int?,
    );
    expect(built, equals(decision),
        reason: 'the app signs exactly the vector, display binding included');
  });

  test('the review record the app builds is the box vector, byte for byte (R-NOTIFY-12)', () async {
    final review = (doc['review'] as Map).cast<String, Object?>();
    final built = reviewDecisionRecord(
      deviceId: review['device_id'] as String,
      reviewId: review['review_id'] as String,
      decision: review['decision'] as String,
      seen: review['seen'] as String,
      ts: review['ts'] as int,
      nonce: review['nonce'] as String,
    );
    expect(built, equals(review));
    expect(
      base64.encode(decisionMessage(built)),
      equals(doc['review_message_b64'] as String),
    );
    final keyPair = await signKeyFromSeed(_hexToBytes(doc['sign_seed_hex'] as String));
    expect(await signBase64(keyPair, decisionMessage(built)), equals(doc['review_signature_b64'] as String));
    // The "missing" sentinel is a signed value too, and the same context carries it.
    final missing = (doc['review_missing'] as Map).cast<String, Object?>();
    final builtMissing = reviewDecisionRecord(
      deviceId: missing['device_id'] as String,
      reviewId: missing['review_id'] as String,
      decision: missing['decision'] as String,
      seen: missing['seen'] as String,
      ts: missing['ts'] as int,
      nonce: missing['nonce'] as String,
    );
    expect(
      base64.encode(decisionMessage(builtMissing)),
      equals(doc['review_missing_message_b64'] as String),
    );
    expect(
      await signBase64(keyPair, decisionMessage(builtMissing)),
      equals(doc['review_missing_signature_b64'] as String),
    );
  });

  test('the ACT records the app builds are the box vectors (R-NOTIFY-13)', () async {
    final keyPair = await signKeyFromSeed(_hexToBytes(doc['sign_seed_hex'] as String));
    final grant = (doc['act_grant'] as Map).cast<String, Object?>();
    final builtGrant = actRecord(
      deviceId: grant['device_id'] as String,
      account: grant['account'] as String,
      action: grant['action'] as String,
      minutes: grant['minutes'] as int,
      ts: grant['ts'] as int,
      nonce: grant['nonce'] as String,
    );
    expect(builtGrant, equals(grant));
    expect(base64.encode(decisionMessage(builtGrant)), equals(doc['act_grant_message_b64'] as String));
    expect(await signBase64(keyPair, decisionMessage(builtGrant)), equals(doc['act_grant_signature_b64'] as String));
    final end = (doc['act_end'] as Map).cast<String, Object?>();
    final builtEnd = actRecord(
      deviceId: end['device_id'] as String,
      account: end['account'] as String,
      action: end['action'] as String,
      ts: end['ts'] as int,
      nonce: end['nonce'] as String,
    );
    expect(builtEnd, equals(end));
    expect(base64.encode(decisionMessage(builtEnd)), equals(doc['act_end_message_b64'] as String));
    expect(await signBase64(keyPair, decisionMessage(builtEnd)), equals(doc['act_end_signature_b64'] as String));
  });

  test('signing with the seed reproduces the recorded signatures', () async {
    final decision = (doc['decision'] as Map).cast<String, Object?>();
    final request = (doc['request'] as Map).cast<String, dynamic>();
    final keyPair = await signKeyFromSeed(_hexToBytes(doc['sign_seed_hex'] as String));
    expect(
      await signBase64(keyPair, decisionMessage(decision)),
      equals(doc['decision_signature_b64'] as String),
    );
    expect(
      await signBase64(
        keyPair,
        requestMessage(
          deviceId: request['device_id'] as String,
          ts: request['ts'] as int,
          nonce: request['nonce'] as String,
          method: request['method'] as String,
          path: request['path'] as String,
          body: base64.decode(request['body_b64'] as String),
        ),
      ),
      equals(doc['request_signature_b64'] as String),
    );
  });

  test('the decision signature verifies over the canonical record', () async {
    final decision = (doc['decision'] as Map).cast<String, Object?>();
    final publicKey = SimplePublicKey(base64.decode(doc['sign_pub_b64'] as String), type: KeyPairType.ed25519);
    final signature = Signature(
      base64.decode(doc['decision_signature_b64'] as String),
      publicKey: publicKey,
    );
    final ok = await Ed25519().verify(decisionMessage(decision), signature: signature);
    expect(ok, isTrue);
  });

  test('the request signature verifies over the request message', () async {
    final request = (doc['request'] as Map).cast<String, dynamic>();
    final message = requestMessage(
      deviceId: request['device_id'] as String,
      ts: request['ts'] as int,
      nonce: request['nonce'] as String,
      method: request['method'] as String,
      path: request['path'] as String,
      body: base64.decode(request['body_b64'] as String),
    );
    expect(base64.encode(message), equals(doc['request_message_b64'] as String));
    final publicKey = SimplePublicKey(base64.decode(doc['sign_pub_b64'] as String), type: KeyPairType.ed25519);
    final signature = Signature(
      base64.decode(doc['request_signature_b64'] as String),
      publicKey: publicKey,
    );
    expect(await Ed25519().verify(message, signature: signature), isTrue);
  });

  test('the pairing proof recomputes from the token', () async {
    final pairing = (doc['pairing'] as Map).cast<String, String>();
    final proof = await pairingProof(
      pairing['token']!,
      pairing['name']!,
      pairing['sign_pub']!,
      pairing['box_pub']!,
    );
    expect(proof, equals(pairing['proof']));
  });

  test('the away envelope opens with the box private key', () async {
    final env = (doc['envelope'] as Map).cast<String, dynamic>();
    final plaintext = await Envelope.open(
      deviceId: 'd-vector',
      boxSeed: _hexToBytes(env['box_priv_hex'] as String),
      envelope: (env['envelope'] as Map).cast<String, Object?>(),
    );
    expect(plaintext, equals(base64.decode(env['plaintext_b64'] as String)));
  });

  test('the envelope rejects another device id (the AAD binds it)', () async {
    final env = (doc['envelope'] as Map).cast<String, dynamic>();
    final sealed = (env['envelope'] as Map).cast<String, Object?>();
    await expectLater(
      Envelope.open(
        deviceId: 'd-other',
        boxSeed: _hexToBytes(env['box_priv_hex'] as String),
        envelope: sealed,
      ),
      throwsA(anything),
    );
  });
}

Uint8List _hexToBytes(String hex) {
  final out = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}
