#!/usr/bin/env python3
"""Generate the shared signing vectors for the parent app and the box (N-8).

The app is not built in this repository yet. These vectors pin the exact bytes
it must sign — a decision record, a relay request, and a pairing proof — so an
implementation in another language can prove it matches `lib/devices.py` byte for
byte. `test/shell.d/notify-vectors-test.sh` fails if this file drifts from the
scheme.

Usage: python3 clients/parent/test-vectors/generate.py [OUT]
"""

import base64
import hashlib
import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "lib"))
import devices  # noqa: E402

from cryptography.hazmat.primitives import serialization  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey  # noqa: E402

_envelope_spec = importlib.util.spec_from_file_location("kids_envelope", os.path.join(ROOT, "lib", "envelope.py"))
envelope = importlib.util.module_from_spec(_envelope_spec)
_envelope_spec.loader.exec_module(envelope)


def b64(raw):
    return base64.b64encode(raw).decode()


def build():
    # A fixed seed: reproducible vectors that carry no real key.
    key = Ed25519PrivateKey.from_private_bytes(bytes(range(32)))
    sign_pub = b64(
        key.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    )
    # A fixed 32-byte box (end-to-end) key; only its string form is used by the
    # pairing proof so far.
    box_pub = b64(bytes(range(64, 96)))

    decision = {
        "device_id": "d-vector",
        "request_id": "1000000001-kid-ada-time",
        "decision": "approve",
        # Non-ASCII, a quote and a backslash on purpose: the canonical form
        # escapes them (\uXXXX, \", \\), the traps a raw encoder and a naive
        # quote handler fall into.
        "reply": 'Après "dîner" \\ ok',
        "ts": 1758530400,
        "nonce": "nonce-decision-1",
    }

    # A review decision (R-NOTIFY-12): the same signer and context, the review
    # record shape, and the `missing` sentinel as `seen` (a removed add-on).
    review = {
        "device_id": "d-vector",
        "review_id": "kid-ada.7d0c67a410c57b10",
        "decision": "approve",
        "seen": "ab" * 32,
        "ts": 1758530400,
        "nonce": "nonce-review-1",
    }
    review_missing = {
        "device_id": "d-vector",
        "review_id": "kid-ada.7d0c67a410c57b10",
        "decision": "deny",
        "seen": "missing",
        "ts": 1758530400,
        "nonce": "nonce-review-2",
    }

    body = b'{"record":{}}'
    request = {
        "device_id": "d-vector",
        "ts": 1758530400,
        "nonce": "nonce-request-1",
        "method": "POST",
        "path": "/v1/requests/1000000001-kid-ada-time/decision",
        "body_sha256": hashlib.sha256(body).hexdigest(),
        "body_b64": b64(body),
    }

    pairing = {
        "token": "00112233445566778899aabbccddeeff00112233",
        "name": "Ada's phone",
        "sign_pub": sign_pub,
        "box_pub": box_pub,
    }
    pairing["proof"] = devices.pairing_proof(
        pairing["token"], pairing["name"], pairing["sign_pub"], pairing["box_pub"]
    )

    # The away envelope (N-11): a fixed X25519 box key, ephemeral key and nonce.
    box_seed = bytes(range(32, 64))
    box_priv = X25519PrivateKey.from_private_bytes(box_seed)
    box_public = b64(
        box_priv.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    )
    eph_seed = bytes(range(64, 96))
    nonce = bytes(range(200, 212))
    plaintext = b'{"kids": [{"kid": "kid-ada", "live": true}]}'
    envelope_doc = {
        "scheme": "x25519-hkdf-sha256-chacha20poly1305-aad-device-id",
        "box_priv_hex": box_seed.hex(),
        "box_pub_b64": box_public,
        "eph_hex": eph_seed.hex(),
        "nonce_hex": nonce.hex(),
        "plaintext_b64": b64(plaintext),
        "envelope": envelope.seal("d-vector", box_public, plaintext, eph_priv=eph_seed, nonce=nonce),
    }

    return {
        "_comment": (
            "Generated by generate.py -- do not edit by hand. Shared by the box "
            "(test/shell.d/notify-vectors-test.sh) and the parent app's tests (N-8)."
        ),
        "contexts_b64": {
            "decision": b64(devices.SIGN_CONTEXT),
            "request": b64(devices.REQUEST_CONTEXT),
        },
        "sign_seed_hex": bytes(range(32)).hex(),
        "sign_seed_note": "a test key only: not a secret, and not registered on any box",
        "sign_pub_b64": sign_pub,
        "box_pub_b64": box_pub,
        "decision": decision,
        "decision_message_b64": b64(devices.canonical(decision)),
        "decision_signature_b64": b64(key.sign(devices.canonical(decision))),
        "review": review,
        "review_message_b64": b64(devices.canonical(review)),
        "review_signature_b64": b64(key.sign(devices.canonical(review))),
        "review_missing": review_missing,
        "review_missing_message_b64": b64(devices.canonical(review_missing)),
        "review_missing_signature_b64": b64(key.sign(devices.canonical(review_missing))),
        "request": request,
        "request_message_b64": b64(
            devices.request_message(
                request["device_id"],
                request["ts"],
                request["nonce"],
                request["method"],
                request["path"],
                body,
            )
        ),
        "request_signature_b64": b64(
            key.sign(
                devices.request_message(
                    request["device_id"],
                    request["ts"],
                    request["nonce"],
                    request["method"],
                    request["path"],
                    body,
                )
            )
        ),
        "pairing": pairing,
        "envelope": envelope_doc,
    }


def main(out_path):
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(build(), f, indent=2, sort_keys=True)
        f.write("\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "notify-vectors.json"))
